version: '2'
services:
  master:
    image: redis:3.2.12
    restart: always
    volumes:
      - ./redis.conf:/redis.conf
    command: redis-server /redis.conf --port 7687 --requirepass "redisweb1123" --masterauth "redisweb1123"
    network_mode: "host"

  sentinel1:
#    build: sentinel
    restart: always
    image: redis-sentinel:26379
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    ports:
      - "26379:26379"
#    links:
#      - master:redis-master
#      - slave
#    network_mode: "host"

